config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  get 'customers/alphabetized'
  get 'customers/missing_email'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :full_name, :phone_number, :notes, presence: true
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  
  def alphabetized
    @customers = Customer.all.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email_address: [nil, ''])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="content">
  <div class="columns">
    <% if !@customers.empty? %>
      <% for customer in @customers %>
        <div class="card">
          <h2><%= customer.full_name %></h2>
          <% if customer.image.present? %>
            <%= image_tag customer.image, class: "image" %>
          <% end %>
          <p><span class="bold">Province:</span><%= customer.notes %></p>
          <p><%= customer.phone_number %></p>
          <p><%= customer.email_address %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<h1>Alphabetized</h1>

<p>
  <%= link_to "Home", root_path %> |
  <%= link_to "Alphabetized", customers_alphabetized_path %> |
  <%= link_to "Missing Email", customers_missing_email_path %>
</p>

<%= render partial: 'customer', object: @customers, locals: {show_link: false} %>

app/views/customers/index.html.erb
<h1>All Customers</h1>

<p>
  <%= link_to "Home", root_path %> |
  <%= link_to "Alphabetized", customers_alphabetized_path %> |
  <%= link_to "Missing Email", customers_missing_email_path %>
</p>

<%= render partial: 'customer', object: @customers, locals: {show_link: false} %>

app/views/customers/missing_email.html.erb
<h1>Missing Email</h1>

<p>
  <%= link_to "Home", root_path %> |
  <%= link_to "Alphabetized", customers_alphabetized_path %> |
  <%= link_to "Missing Email", customers_missing_email_path %>
</p>

<%= render partial: 'customer', object: @customers, locals: {show_link: false} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmChallange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>